<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<img style="position:absolute;top:0.00in;left:0.00in;width:9.27in;height:14.18in" src="ri_1.png" />
<div style="position:absolute;top:1.15in;left:5.75in;width:1.33in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">CSC Regional Office X</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.54in;left:5.97in;width:0.90in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">March 26, 2023</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.95in;left:5.88in;width:1.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">OROQUIETA CITY</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.36in;left:0.93in;width:0.98in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000">BUGTONG</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.36in;left:3.95in;width:1.17in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000">ALMIRA JOY</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.36in;left:7.38in;width:0.50in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000">ONIS</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.36in;left:8.73in;width:0.24in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000">O.</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:0.34in;width:0.23in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">23</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:1.34in;width:0.88in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">10/07/1999</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:3.19in;width:0.62in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">Female</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:5.97in;width:1.12in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">OZAMIS CITY</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.05in;left:0.89in;width:0.75in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">FILIPINO</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.05in;left:3.21in;width:0.45in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">ONIS</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.05in;left:5.86in;width:0.48in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">JUVY</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.05in;left:8.09in;width:0.48in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">JALA</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.40in;left:0.26in;width:3.64in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">PUROK-7 MOLATUHAN BAJO LOPEZ JAENA</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.40in;left:8.25in;width:0.42in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">7208</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.72in;left:0.59in;width:0.37in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">1.42</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.72in;left:1.65in;width:0.23in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">52</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.72in;left:3.47in;width:0.55in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">Single</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.72in;left:6.43in;width:1.32in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">Not Applicable -</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.08in;left:1.12in;width:1.07in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">09056443420</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.08in;left:4.13in;width:0.97in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">9632381042</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.08in;left:6.43in;width:2.43in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000">almirajoybugtong@gmail.com</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.52in;left:1.33in;width:0.41in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">College</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:1.12in;width:0.64in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Graduated</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:5.84in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.90in;left:4.25in;width:0.64in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">09/02/2022</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.90in;left:6.31in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.16in;left:3.48in;width:2.88in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">BACHELOR OF TECHNOLOGY AND LIVELIHOOD EDUCATION</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.16in;left:6.79in;width:1.13in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">INDUSTRIAL ARTS</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.37in;left:2.19in;width:4.75in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">UNIVERSITY OF SCIENCE AND TECHNOLOGY OF SOUTHERN PHILIPPINES , OROQUIETA CITY</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.37in;left:8.06in;width:0.61in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">2018-2022</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:2.54in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:5.41in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:6.55in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:8.14in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.59in;left:2.54in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.59in;left:5.41in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.59in;left:6.55in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.59in;left:8.14in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.96in;left:0.47in;width:0.75in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Government</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.56in;left:0.83in;width:0.96in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">MEEDO OFFICE</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.57in;left:2.61in;width:2.00in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">EASTERN POBLACION, LOPEZ JAENA</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.57in;left:5.09in;width:0.99in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">DATA GATHERING</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.57in;left:6.97in;width:0.09in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">0</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.57in;left:8.14in;width:0.42in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">ACTIVE</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.26in;left:0.90in;width:0.22in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">No</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.50in;left:6.10in;width:0.22in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">No</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.67in;left:1.80in;width:0.27in;line-height:0.16in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">N/A</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.99in;left:6.92in;width:1.44in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">LEAH CENTILAS 12/18/2022</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.05in;left:2.69in;width:0.78in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">March 26, 2023</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.04in;left:5.96in;width:1.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">OROQUIETA CITY</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.28in;left:2.58in;width:0.88in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">LEAH CENTILAS</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.28in;left:6.01in;width:0.56in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">12/18/2022</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.97in;left:2.24in;width:0.98in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">ALMIRA JOY</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.97in;left:4.28in;width:0.20in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">O.</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.97in;left:5.50in;width:0.82in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">BUGTONG</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:13.25in;left:0.94in;width:0.56in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Female</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:13.25in;left:3.94in;width:0.80in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">10/07/1999</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.47in;left:7.52in;width:1.50in;height:1.93in" src="ri_2.jpeg" />
<img style="position:absolute;top:13.68in;left:7.52in;width:1.50in;height:1.93in" src="ri_3.jpeg" />
</body>
</html>
